FISOLUTION/iluvit-backend

src/main/resources/application.yml

Reverts FISOLUTION/ILUVIT_BACK#241

Revert "[UPDATE] yml change"

---

src/main/java/FIS/iLUVit/dto/center/CenterBannerDto.java

Reverts FISOLUTION/ILUVIT_BACK#246

Revert "[fix] starAverage 부분 둘째자리에서 반올림 하도록 변경"

---

src/main/java/FIS/iLUVit/event/AlarmEvent.java
src/main/java/FIS/iLUVit/event/ExpoServerUtils.java
src/main/java/FIS/iLUVit/event/dto/ExpoServerResponse.java
src/main/java/FIS/iLUVit/event/eventListener/AlarmEventHandler.java
src/main/java/FIS/iLUVit/service/CommentService.java
src/main/java/FIS/iLUVit/service/ParticipationService.java

- Related to: #253
- 푸시 알림 관련 오류 수정
- 필요없는 로그 코드 삭제

[DEL] 푸시관련 로그 코드 삭제 #253

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

- Related to: #249 
- webhook을 생성하여 포스트맨에서 에러 발생 시 에러 코드 슬랙에 반환하여 에러 코드 기록 관리
- webhook 완성
- 없음

[ADD] application, logback 코드 정리 #249

---

src/main/java/FIS/iLUVit/domain/Participation.java
src/main/java/FIS/iLUVit/domain/Waiting.java
src/main/java/FIS/iLUVit/event/ExpoServerUtils.java
src/main/java/FIS/iLUVit/event/eventListener/AlarmEventHandler.java
src/main/java/FIS/iLUVit/event/eventListener/ParticipationCancelEventHandler.java
src/main/java/FIS/iLUVit/service/ChatService.java
src/main/java/FIS/iLUVit/service/ChildService.java
src/main/java/FIS/iLUVit/service/ParticipationService.java
src/main/java/FIS/iLUVit/service/PresentationService.java
src/main/java/FIS/iLUVit/service/TeacherService.java

[FIX] AlarmRepository.save() 오류 해결 #264

---

src/main/java/FIS/iLUVit/service/AlarmService.java

[FIX] ci 오류 해결 #264

---

src/main/java/FIS/iLUVit/dto/presentation/PresentationForUserDto.java
src/main/java/FIS/iLUVit/dto/presentation/PresentationForUserResponse.java
src/main/java/FIS/iLUVit/repository/PresentationRepositoryCustomImpl.java

- Related to: #269 
- 필터 기반 설명회 검색 API 에 ex) 금천구 같이 시/군/구를 주는 필드를 dto에 추가

[FEAT] 필터 기반 설명회 검색에 지번주소 추가 #269

---

src/main/java/FIS/iLUVit/config/IluvitJpaConfig.java

Reverts FISOLUTION/BE_ILUVIT#278

Revert "feature/#273"

---

src/main/java/FIS/iLUVit/controller/CenterController.java
src/main/java/FIS/iLUVit/domain/Center.java
src/main/java/FIS/iLUVit/domain/Presentation.java
src/main/java/FIS/iLUVit/dto/center/CenterBannerDto.java
src/main/java/FIS/iLUVit/repository/CenterBookmarkRepository.java
src/main/java/FIS/iLUVit/repository/CenterRepository.java
src/main/java/FIS/iLUVit/repository/CenterRepositoryImpl.java
src/main/java/FIS/iLUVit/repository/ChildRepository.java
src/main/java/FIS/iLUVit/repository/ReviewRepository.java
src/main/java/FIS/iLUVit/repository/TeacherRepository.java
src/main/java/FIS/iLUVit/repository/UserRepository.java
src/main/java/FIS/iLUVit/service/CenterService.java
src/main/java/FIS/iLUVit/service/ChildService.java
src/main/java/FIS/iLUVit/service/ReviewService.java
src/main/java/FIS/iLUVit/service/TeacherService.java
src/test/java/FIS/iLUVit/repository/ReviewRepositoryTest.java
src/test/java/FIS/iLUVit/service/ReviewServiceTest.java

Reverts FISOLUTION/BE_ILUVIT#275

Revert "Feature/#274"

---

src/main/java/FIS/iLUVit/dto/board/BoardListDto.java
src/main/java/FIS/iLUVit/repository/BoardBookmarkRepository.java
src/main/java/FIS/iLUVit/service/BoardService.java
src/main/resources/application.yml

- Related to: 286
- 게시판 조회 코드 리팩토링

[REFACTOR] 게시판 조회 코드 리팩토링 #286

---

src/main/java/FIS/iLUVit/config/WebConfig.java

[FIX] cors 오류 해결

---

src/main/java/FIS/iLUVit/config/SecurityConfig.java

[FEAT] 스프링 시큐리티 리소스 권한 설정 추가

---

src/main/java/FIS/iLUVit/domain/reports/Report.java
src/main/java/FIS/iLUVit/domain/reports/ReportDetail.java

- Related to: #291 
-  불필요한 연관관계를 삭제한다

[DEL] report reportDetail 필드 삭제 #291

---

src/main/java/FIS/iLUVit/controller/AlarmController.java
src/main/java/FIS/iLUVit/dto/alarm/AlarmDetailResponseDto.java
src/main/java/FIS/iLUVit/dto/alarm/AlarmReadResponseDto.java
src/main/java/FIS/iLUVit/dto/alarm/AlarmResponseDto.java
src/main/java/FIS/iLUVit/exception/exceptionHandler/ErrorResponse.java
src/main/java/FIS/iLUVit/repository/AlarmRepository.java
src/main/java/FIS/iLUVit/service/AlarmService.java
src/test/java/FIS/iLUVit/controller/AuthControllerTest.java

[REFACTOR] Alarm Controller, Respository, Service 리팩토링

---

src/main/java/FIS/iLUVit/controller/AuthController.java
src/main/java/FIS/iLUVit/controller/BoardBookmarkController.java
src/main/java/FIS/iLUVit/controller/BoardController.java
src/main/java/FIS/iLUVit/controller/ChatController.java
src/main/java/FIS/iLUVit/controller/ChildController.java
src/main/java/FIS/iLUVit/dto/auth/AuthFindPasswordDto.java
src/main/java/FIS/iLUVit/dto/auth/AuthLoginIdDto.java
src/main/java/FIS/iLUVit/dto/board/BoardCreateDto.java
src/main/java/FIS/iLUVit/dto/board/BoardRequestDto.java
src/main/java/FIS/iLUVit/dto/board/BoardStoryDto.java
src/main/java/FIS/iLUVit/dto/board/BoardStoryPreviewDto.java
src/main/java/FIS/iLUVit/dto/chat/ChatListDto.java
src/main/java/FIS/iLUVit/dto/chat/ChatRequestDto.java
src/main/java/FIS/iLUVit/dto/chat/ChatRoomDto.java
src/main/java/FIS/iLUVit/dto/chat/ChatRoomRequestDto.java
src/main/java/FIS/iLUVit/dto/child/ChildDetailRequest.java
src/main/java/FIS/iLUVit/dto/child/ChildDetailResponse.java
src/main/java/FIS/iLUVit/dto/child/ChildDto.java
src/main/java/FIS/iLUVit/dto/child/ChildInfoForAdminDto.java
src/main/java/FIS/iLUVit/repository/ChildRepository.java
src/main/java/FIS/iLUVit/repository/TeacherRepository.java
src/main/java/FIS/iLUVit/service/AuthService.java
src/main/java/FIS/iLUVit/service/BoardBookmarkService.java
src/main/java/FIS/iLUVit/service/BoardService.java
src/main/java/FIS/iLUVit/service/ChatService.java
src/main/java/FIS/iLUVit/service/ChildService.java
src/main/java/FIS/iLUVit/service/PostService.java

[REFACTOR] Child End-to-end 리팩토링 

---

src/main/java/FIS/iLUVit/controller/ExpoTokenController.java
src/main/java/FIS/iLUVit/domain/ExpoToken.java
src/main/java/FIS/iLUVit/dto/expoToken/ExpoTokenCreateDto.java
src/main/java/FIS/iLUVit/dto/expoToken/ExpoTokenDeviceIdDto.java
src/main/java/FIS/iLUVit/dto/expoToken/ExpoTokenDto.java
src/main/java/FIS/iLUVit/dto/expoToken/ExpoTokenRequest.java
src/main/java/FIS/iLUVit/event/eventListener/AlarmEventHandler.java
src/main/java/FIS/iLUVit/repository/ExpoTokenRepository.java
src/main/java/FIS/iLUVit/service/ExpoTokenService.java

[HOTFIX] ExpoToken 관련 api 추가 및 수정

---

src/main/java/FIS/iLUVit/config/SecurityConfig.java

- Related to: #344 
- expoToken 비활성화 api ( /expo-token/deactive )는 토큰 없이 사용 할 수 있도록 permitAll() 해준다

[CHORE] SecurityConfig 권한 수정 #344

---

src/main/java/FIS/iLUVit/domain/Post.java
src/main/java/FIS/iLUVit/service/PostHeartService.java

[FIX] 게시글 좋아요 개수가 반영되지 않는 문제 해결 #355

---

src/main/java/FIS/iLUVit/service/ScheduledNotificationService.java

- Related to: #363 
- 현장요원 방문 알림 테스트 환경 조성

[TEST] 현장요원 방문 알림 테스트 #363

---

src/main/java/FIS/iLUVit/service/ScheduledNotificationService.java

Reverts FISOLUTION/iluvit-backend#364

Revert "[TEST] 현장요원 방문 알림 테스트 #363"

---

src/main/java/FIS/iLUVit/domain/BlackUser.java
src/main/java/FIS/iLUVit/domain/enumtype/UserStatus.java

- Related to: closed #372 
- 블랙유저 도메인을 개발합니다

[FEAT] 블랙유저 도메인 개발

---

src/main/java/FIS/iLUVit/domain/BlackUser.java
src/main/java/FIS/iLUVit/domain/Parent.java
src/main/java/FIS/iLUVit/domain/Teacher.java
src/main/java/FIS/iLUVit/domain/User.java
src/main/java/FIS/iLUVit/exception/UserErrorResult.java
src/main/java/FIS/iLUVit/repository/BlackUserRepository.java
src/main/java/FIS/iLUVit/service/BlackUserService.java
src/main/java/FIS/iLUVit/service/ParentService.java
src/main/java/FIS/iLUVit/service/TeacherService.java
src/main/java/FIS/iLUVit/service/UserService.java

- close #376 
- 로그인 api : 에러 로직 추가
- 자동로그인 ( 유저 조회 ) api : 에러 로직 추가
- 회원가입 api : 에러 로직 추가
- 탈퇴 api : 블랙 유저에 정보 저장하는 로직 추가

[FEAT] Black User 관련 로직 추가

---

src/main/java/FIS/iLUVit/repository/BlackUserRepository.java
src/main/java/FIS/iLUVit/service/AuthService.java
src/main/java/FIS/iLUVit/service/UserService.java

- close #376 
- 닉네임 중복 확인 api : 에러 로직 추가
- 로그인 아이디 중복 확인 api : 에러 로직 추가
- 회원가입을 위한 인증번호 전송 api : 에러 로직 추가

[FEAT] Black User 관련 로직 추가 

---

src/main/java/FIS/iLUVit/domain/BlackUser.java
src/main/java/FIS/iLUVit/repository/BlackUserRepository.java

- close #386 
- 정책이 변경되어 관리자에 의한 이용제한 타입을 삭제하고 일주일간 이용제한으로 수정해 확장성을 제공하였습니다. 해당 enum 클래스의 속성 변경으로 인한 리포지토리 코드를 수정합니다
-

[FEAT] 정책변경으로 인한 BlackUserRepository 쿼리메소드 수정

---

src/main/java/FIS/iLUVit/repository/BlackUserRepository.java
src/main/java/FIS/iLUVit/service/BlackUserService.java
src/main/java/FIS/iLUVit/service/UserService.java

- close #386 
- 로그인 시도 시 회원탈퇴 상태인 차단된 유저인지도 에러로 반환
-

[FEAT] 로그인 에러처리 변경

---

src/main/java/FIS/iLUVit/domain/User.java
src/main/java/FIS/iLUVit/domain/enumtype/UserStatus.java
src/main/java/FIS/iLUVit/repository/BlackUserRepository.java
src/main/java/FIS/iLUVit/service/BlackUserService.java

- close #380
-  15일 뒤 UserStatus가 WITHDRAWN인 blackUser 삭제
-  7일 뒤 UserStatus가 RESTRICTED_REPORT인 blackUser 삭제 및 User로 복귀
- 6개월 뒤 UserStatus가 RESTRICTED_ADMIN 인 blakcUser 삭제

[FEAT] Scheduler 사용하여 BlackUser 삭제

---

src/main/java/FIS/iLUVit/domain/Blocked.java

- close #389 
- Blocked domain 생성

[FEAT] Blocked 도메인 생성

---

src/main/java/FIS/iLUVit/repository/BlockedRepository.java

- close #389 
- BlockedRepository 생성

[FEAT] BlockedRepository 생성

---

src/main/java/FIS/iLUVit/controller/BlockedController.java
src/main/java/FIS/iLUVit/domain/Blocked.java
src/main/java/FIS/iLUVit/exception/BlockedErrorResult.java
src/main/java/FIS/iLUVit/exception/BlockedException.java
src/main/java/FIS/iLUVit/exception/PostErrorResult.java
src/main/java/FIS/iLUVit/repository/AlarmRepository.java
src/main/java/FIS/iLUVit/repository/BlockedRepository.java
src/main/java/FIS/iLUVit/repository/PostRepository.java
src/main/java/FIS/iLUVit/service/BlockedService.java

- close #391 
- 유저 차단 API 구현
- 차단된 유저 관련 알림 삭제 로직 구현
- 저희 앞으로 차차 빌더패턴 적용할 계획이 있으니 이번 API에서는 빌더패턴 적용하여 Blocked를 생성해주었습니다!

[FEAT] 유저차단 API 구현

---

src/main/java/FIS/iLUVit/domain/Blocked.java
src/main/java/FIS/iLUVit/exception/BlockedErrorResult.java
src/main/java/FIS/iLUVit/exception/exceptionHandler/controllerAdvice/GlobalControllerAdvice.java
src/main/java/FIS/iLUVit/repository/PostRepository.java
src/main/java/FIS/iLUVit/service/BlockedService.java

- close #391 
- `자기 자신을 차단할 수는 없습니다.`
- 빌더패턴 createBlocked 추가

[FIX] 유저 차단 API 적절한 에러처리

---

src/main/java/FIS/iLUVit/repository/BoardBookmarkRepository.java
src/main/java/FIS/iLUVit/service/BoardBookmarkService.java

- close #392
- 즐겨찾는 게시판 전체 조회 로직 추가 ( getAllBoardBookmark )

[FEAT] 즐겨찾는 게시판 전체 조회 로직 추가

---

src/main/java/FIS/iLUVit/controller/ReportController.java
src/main/java/FIS/iLUVit/repository/ReportDetailRepository.java
src/main/java/FIS/iLUVit/repository/ReportRepository.java
src/main/java/FIS/iLUVit/service/ReportService.java

[REFACTOR] Report End-to-end 리팩토링

---

src/main/java/FIS/iLUVit/repository/BoardBookmarkRepository.java
src/main/java/FIS/iLUVit/repository/PostRepository.java
src/main/java/FIS/iLUVit/repository/PostRepositoryCustom.java
src/main/java/FIS/iLUVit/repository/PostRepositoryImpl.java
src/main/java/FIS/iLUVit/service/BoardBookmarkService.java
src/main/java/FIS/iLUVit/service/PostService.java

- close #392 
- jpa not in 컬렉션 파라미터 문제 해결
- 모두의 이야기, 시설별 이야기 전체 조회 쿼리 오류 수정

[FIX] 유저차단 기능 관련 게시글, 댓글 로직 오류 수정

---

src/main/java/FIS/iLUVit/event/eventListener/AlarmEventHandler.java
src/main/java/FIS/iLUVit/repository/AlarmRepository.java
src/main/java/FIS/iLUVit/repository/AuthRepository.java
src/main/java/FIS/iLUVit/repository/BoardRepository.java
src/main/java/FIS/iLUVit/repository/CenterBookmarkRepository.java
src/main/java/FIS/iLUVit/repository/CenterRepository.java
src/main/java/FIS/iLUVit/repository/ChildRepository.java
src/main/java/FIS/iLUVit/repository/CommentRepository.java
src/main/java/FIS/iLUVit/repository/ParentRepository.java
src/main/java/FIS/iLUVit/repository/PresentationRepository.java
src/main/java/FIS/iLUVit/repository/ReportDetailRepository.java
src/main/java/FIS/iLUVit/repository/ReportRepository.java
src/main/java/FIS/iLUVit/repository/ScrapPostRepository.java
src/main/java/FIS/iLUVit/repository/ScrapRepository.java
src/main/java/FIS/iLUVit/repository/TeacherRepository.java
src/main/java/FIS/iLUVit/repository/TokenPairRepository.java
src/main/java/FIS/iLUVit/repository/UserRepository.java

- close #410
- 아이추가 관련 Repository 쿼리 띄어쓰기 문제 해결

[FIX] 아이 추가 api 오류 해결

---

src/main/java/FIS/iLUVit/domain/User.java

[FIX] User dtype @Column 제약조건 추가

---

src/main/java/FIS/iLUVit/service/PostService.java

- close #422
- release 브랜치에서 /post/${post_id} - 차단한 유저의 댓글 isBlocked가 false로 오는 문제 해결

[FIX] isBlocked 필드 오류 해결 

---

.github/workflows/dev_deploy.yml
.gitignore

- close #419
- cd 가 안되는 문제를 해결하기 위에 ci 파일에 gitignore한 logs/error, logs/data 만드는 코드를 추가하였다

[FEAT] logs 폴더 만드는 코드 추가

---

.github/workflows/dev_deploy.yml

[CHORE] logs 폴더 만드는 코드 수정 #419

---

.github/workflows/dev_deploy.yml

- close #419
- ci 실패로 인해 dev_deploy의 logs 폴더 만드는 코드 수정
-

[CHORE] logs 폴더 만드는 코드 수정

---

.github/workflows/dev_deploy.yml
.gitignore

[FIX] gitigonre에서 logs 제거 #419

---

.github/workflows/dev_deploy.yml
.gitignore
logs/data/data_20230822.log

[FIX] gitigonre에서 logs 제거

---

src/main/resources/logback-spring.xml

Reverts FISOLUTION/iluvit-backend#436

Revert "[DELETE] logback-spring.xml in github"

---

.github/workflows/dev_deploy.yml
.github/workflows/prod_deploy.yml
.gitignore

Reverts FISOLUTION/iluvit-backend#435

Revert " [FIX] logback 파일 gitignore"

---

src/main/java/FIS/iLUVit/dto/board/StoryPreviewDto.java

- close #444 
- 이야기 전체 조회 응답객체에 시설 프로필 이미지 필드를 추가합니다

[FEAT] 이야기 전체 조회 시 시설 프로필 이미지 추가

---

src/main/java/FIS/iLUVit/dto/comment/CommentResponse.java
src/main/java/FIS/iLUVit/repository/CommentRepository.java
src/main/java/FIS/iLUVit/service/PostService.java

- close #454 
-  게시글 상세 조회 api 에서 댓글 조회 로직 수정

[FIX] 대댓글이 중복으로 조회되는 오류

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

- close #457
-  local profile 삭제, dev,prod 프로필 로컬 logs 경로 ./logs로 수정 ( secret 파일들은 그대로 우분투 경로 유지 )
-  application.yml 수정
- logback-spring.xml 수정

[REFACTOR] local profile 삭제 #457

---

src/main/java/FIS/iLUVit/service/PostService.java

- close #459 
-  게시글 상세 조회 api ( post/{postId} ) canDelete 필드 오류 해결
-

[FIX] canDelete 필드 오류 수정

---

src/main/java/FIS/iLUVit/exception/exceptionHandler/controllerAdvice/GlobalControllerAdvice.java

- close #480 
- 데이터 바인딩 관련 에러 메시지를 직접 클라이언트에 노출하지 않았는데 직접 노출하는 방식으로 변경한다
- 이후 클라이언트에서 제대로 처리가 이루어지면 다시 바꿔야 함!

 [REFACTOR] 데이터 바인딩 에러 response 변경

---

src/main/java/FIS/iLUVit/domain/User.java

- close #483
- 유저 도메인의 deletePersonalInfo 함수에서` location = null `삭제

[FEAT] 회원탈퇴 시 통계를 위한 시도 정보 남기기

---

src/main/java/FIS/iLUVit/repository/UserRepository.java
src/main/java/FIS/iLUVit/service/UserService.java

- close #486
- 로그인 아이디와 비밀번호로 유저를 가져오는 코드를 수정한다

[FIX] 로그인 api 비밀번호 해싱 문제 해결 
